dependencies:
  build:
    - python:3.6.3
    - homebrew:2.1.7

build_targets:
  - name: default
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
      - MM_TYPE=b2bua 
      - MM_BRANCH=master 
      - RTPP_BRANCH=master 
      - RTPPC_TYPE=udp
     
ci:
  builds:
    - name: default
      build_target: default
